.gitignore, pom.xml, src/main/java/sh/ball/audio/AudioPlayer.java, src/main/java/sh/ball/audio/FrameProducer.java, src/main/java/sh/ball/audio/FrameSet.java, src/main/java/sh/ball/audio/Renderer.java, src/main/java/sh/ball/gui/Controller.java, src/main/java/sh/ball/parser/obj/ObjFrameSet.java, src/main/java/sh/ball/parser/obj/ObjParser.java, src/main/java/sh/ball/shapes/Shape.java, src/main/java/sh/ball/shapes/ShapeFrameSet.java, src/main/resources/fxml/osci-render.fxml
This adds the long-needed feature of recording the currently displayed audio to a file for later playback.
A 'Record' button has been added to the GUI that records to a buffer and then writes to a file of your choosing once 'Stop Recording' is pressed.
The file created is referred to in the GUI.
=> Allow audio recording to a .wav file

.gitignore, pom.xml, src/main/java/sh/ball/audio/engine/SimpleAudioDevice.java, src/main/java/sh/ball/gui/Controller.java, src/main/java/sh/ball/parser/ParserFactory.java, src/main/java/sh/ball/parser/txt/TextParser.java, src/main/resources/css/main.css, src/main/resources/fxml/osci-render.fxml
Details in linked pull request, screenshot below:
=> Save and load project configuration to/from file

pom.xml, src/main/java/sh/ball/audio/AudioPlayer.java, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/audio/engine/SimpleAudioDevice.java, src/main/java/sh/ball/audio/engine/XtAudioEngine.java, src/main/java/sh/ball/audio/midi/MidiNote.java, src/main/java/sh/ball/gui/controller/ImageController.java, src/main/java/sh/ball/gui/controller/MainController.java
- Notes now actually have separate volumes
- Playback is much more stable
- More complicated MIDI files can be played
- Allow selection of the instrument that renders the object
- Maybe have a think about how volume works for the object?
- Currently we are using image visibility which has drawbacks
=> Major rework of MIDI playback

pom.xml, src/main/java/sh/ball/audio/AudioPlayer.java, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/audio/midi/MidiNote.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/resources/fxml/main.fxml
- MIDI Channels are now recognised!
- MIDI playback sounds much more correct now
- Pitch bend is now applied per channel
- NOTE_ON messages with 0 velocity now correctly treated as NOTE_OFF messages
=> Add support for MIDI channels, and improve MIDI implementation

.github/workflows/release.yml, CHANGELOG.md, pom.xml, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/engine/Camera.java, src/main/java/sh/ball/engine/CameraDrawKernel.java, src/main/java/sh/ball/engine/Vector3.java, src/main/java/sh/ball/engine/WorldObject.java, src/main/java/sh/ball/gui/controller/GeneralController.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/java/sh/ball/gui/controller/ObjController.java, src/main/java/sh/ball/parser/obj/ObjFrameSettings.java, src/main/java/sh/ball/parser/obj/ObjFrameSource.java, src/main/java/sh/ball/parser/obj/ObjSettingsFactory.java, src/main/java/sh/ball/shapes/CubicBezierCurve.java, src/main/java/sh/ball/shapes/Ellipse.java, src/main/java/sh/ball/shapes/Line.java, src/main/java/sh/ball/shapes/Shape.java, src/main/java/sh/ball/shapes/Vector2.java, src/main/resources/fxml/effects.fxml, src/main/resources/fxml/general.fxml, src/main/resources/fxml/image.fxml, src/main/resources/fxml/main.fxml, src/main/resources/fxml/obj.fxml
- Introduced GPU-based processing of objects
- THIS IS POTENTIALLY UNSTABLE - PLEASE REPORT ANY ISSUES
- Added option to remove hidden edges from meshes
- This can be toggled in View > Hide Hidden Edges
- Moved device options and recording options to Audio on the menu bar
- Reshuffled interface to reduce height and increase length of sliders
=> Introduce GPU-based processing and allow hidden edges to be removed

.github/workflows/release.yml, CHANGELOG.md, pom.xml, src/main/java/sh/ball/engine/CameraDrawKernel.java
- Revert to CPU execution if an exception occurs when trying to use GPU
=> Revert to CPU execution if GPU execution fails

CHANGELOG.md, pom.xml, src/main/java/sh/ball/audio/engine/JavaAudioEngine.java, src/main/java/sh/ball/gui/controller/GeneralController.java, src/main/java/sh/ball/gui/controller/MainController.java
=> Make interface useable whilst loading files

CHANGELOG.md, pom.xml, src/main/java/sh/ball/audio/AudioPlayer.java, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/audio/engine/AudioEngine.java, src/main/java/sh/ball/audio/engine/ConglomerateAudioEngine.java, src/main/java/sh/ball/audio/engine/JavaAudioEngine.java, src/main/java/sh/ball/audio/engine/XtAudioEngine.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/resources/fxml/main.fxml
- Add option Audio > High Audio Stability
- This increases audio latency but significantly improves audio stability - especially on lower-end machines
=> Add toggle to increase audio latency + stability

CHANGELOG.md, pom.xml, src/main/java/sh/ball/gui/FourParamRunnable.java, src/main/java/sh/ball/gui/ThreeParamRunnable.java, src/main/java/sh/ball/gui/components/EffectComponentGroup.java, src/main/java/sh/ball/gui/components/EffectComponentGroupController.java, src/main/java/sh/ball/gui/controller/EffectsController.java, src/main/java/sh/ball/gui/controller/GeneralController.java, src/main/java/sh/ball/gui/controller/ImageController.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/java/sh/ball/gui/controller/ObjController.java, src/main/java/sh/ball/gui/controller/SubController.java, src/main/java/sh/ball/parser/ParserFactory.java, src/main/resources/css/main.css, src/main/resources/fxml/effectComponentGroup.fxml, src/main/resources/fxml/effects.fxml, src/main/resources/fxml/image.fxml
- Add spinners to all effect sliders
- Add spinner to frequency slider
=> Overhaul and refactoring of sliders and spinners for effects and frequency

CHANGELOG.md, pom.xml, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/audio/effect/BitCrushEffect.java, src/main/java/sh/ball/audio/effect/WobbleEffect.java, src/main/java/sh/ball/audio/engine/JavaAudioInput.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/java/sh/ball/shapes/Line.java, src/main/java/sh/ball/shapes/Vector2.java
- Various optimisations
- Mic-based control is now slightly smoother
=> Various optimisations

.gitignore, CHANGELOG.md, pom.xml, src/main/java/sh/ball/audio/AudioPlayer.java, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/audio/engine/AudioEngine.java, src/main/java/sh/ball/audio/engine/ConglomerateAudioEngine.java, src/main/java/sh/ball/audio/engine/JavaAudioEngine.java, src/main/java/sh/ball/audio/engine/XtAudioEngine.java, src/main/java/sh/ball/gui/Gui.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/resources/fxml/main.fxml
- Massively improve audio stability on Mac
- Remove audio stability toggle as no longer needed!
=> Audio stability improvements for Mac

CHANGELOG.md, pom.xml, src/main/java/sh/ball/audio/AudioPlayer.java, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/gui/controller/ImageController.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/resources/fxml/image.fxml, src/main/resources/fxml/main.fxml
- Fix various bugs with MIDI synthesis
- Attack and decay now applied to sine waves in background
- MIDI synthesis now sounds far cleaner
- MIDI attack and decay is now configurable from the MIDI menu
=> MIDI revamp

CHANGELOG.md, pom.xml, src/main/java/sh/ball/gui/components/EffectComponentGroupController.java, src/main/java/sh/ball/gui/controller/EffectsController.java, src/main/java/sh/ball/gui/controller/GeneralController.java, src/main/java/sh/ball/gui/controller/ImageController.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/java/sh/ball/gui/controller/ObjController.java, src/main/java/sh/ball/gui/controller/SubController.java
Bug fix: MIDI CC signals can now be used to change frequency slider
Closes #69
=> MIDI CC signals can now be used to change frequency slider

CHANGELOG.md, pom.xml, src/main/java/sh/ball/gui/controller/MainController.java, src/main/resources/fxml/main.fxml
- Double-click of slider resets value to 0 rather than min
=> Reset slider value to 0 on double-click

CHANGELOG.md, pom.xml, src/main/java/sh/ball/gui/components/CodeEditor.java, src/main/resources/fxml/main.fxml
Bug fix: Fix FileSystemNotFoundException on start-up due to faulty loading of code editor file
=> Fix FileSystemNotFoundException bug

.gitignore, CHANGELOG.md, pom.xml, src/main/java/sh/ball/audio/FrequencyAnalyser.java, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/audio/engine/ConglomerateAudioEngine.java, src/main/java/sh/ball/audio/engine/JavaAudioEngine.java, src/main/java/sh/ball/audio/engine/JavaAudioInput.java, src/main/java/sh/ball/audio/engine/XtAudioEngine.java, src/main/java/sh/ball/audio/midi/MidiCommunicator.java, src/main/java/sh/ball/engine/CameraDrawKernel.java, src/main/java/sh/ball/engine/ObjectServer.java, src/main/java/sh/ball/engine/WorldObject.java, src/main/java/sh/ball/gui/Gui.java, src/main/java/sh/ball/gui/components/EffectComponentGroup.java, src/main/java/sh/ball/gui/controller/GeneralController.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/java/sh/ball/parser/lua/LuaSampleSource.java, src/main/java/sh/ball/parser/svg/SvgParser.java, src/main/resources/fxml/main.fxml
Add error logging to the directory osci-render is run from `/logs/`
=> Add logging to a file for all exceptions

CHANGELOG.md, pom.xml, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/gui/components/EffectComponentGroupController.java, src/main/java/sh/ball/gui/controller/EffectsController.java, src/main/java/sh/ball/gui/controller/GeneralController.java, src/main/java/sh/ball/gui/controller/ImageController.java, src/main/java/sh/ball/gui/controller/LuaController.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/java/sh/ball/gui/controller/ObjController.java, src/main/java/sh/ball/gui/controller/SubController.java, src/main/resources/fxml/main.fxml
Fix potential bug with updating frequency spinner and slider from not-GUI thread
=> Improved frequency slider spinner

CHANGELOG.md, pom.xml, src/main/java/sh/ball/engine/Camera.java, src/main/java/sh/ball/engine/CameraDrawKernel.java, src/main/java/sh/ball/engine/WorldObject.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/java/sh/ball/gui/controller/ObjController.java, src/main/java/sh/ball/parser/obj/ObjFrameSettings.java, src/main/java/sh/ball/parser/obj/ObjFrameSource.java, src/main/java/sh/ball/parser/obj/ObjSettingsFactory.java, src/main/resources/fxml/main.fxml
Make GPU rendering toggleable to prevent crashes due to bad initialisation
=> Make GPU rendering toggleable to prevent crashes due to bad initialisation

pom.xml, src/main/java/sh/ball/audio/engine/XtAudioEngine.java
- SNAPSHOT build for testing only
=> Use JACK by default if available on linux

pom.xml, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/gui/Gui.java, src/main/resources/CHANGELOG.md, src/main/resources/fxml/projectSelect.fxml
- Closes #102 which caused errors when using trace min and small focal lengths at the same time
- Reduce max log file size to 1MiB (was previously unlimited)
=> Fix focal point + min trace issue and increment version number

pom.xml, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/audio/effect/PerspectiveEffect.java, src/main/java/sh/ball/audio/engine/XtAudioEngine.java, src/main/java/sh/ball/gui/Gui.java, src/main/java/sh/ball/gui/controller/EffectsController.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/java/sh/ball/parser/lua/LuaExecutor.java, src/main/java/sh/ball/parser/lua/LuaParser.java, src/main/java/sh/ball/parser/lua/LuaSampleSource.java, src/main/resources/CHANGELOG.md, src/main/resources/fxml/effects.fxml, src/main/resources/fxml/main.fxml, src/main/resources/fxml/projectSelect.fxml
- Allow the 3D perspective effect to be live-programmed with Lua
- By default, the behaviour is the same as before and the image is not modified
- Variables `x`, `y`, and `z` are available to used to transform the 3D position of the image
- `step` is also available as with regular live-coding
- This lets you animate the effects you apply
- Most interesting transformations include modifying the depth to be a function of `x` and `y`
- Example: `return { x, y, z + 0.1 * math.sin(x * 10 + step / 100000) }`
- This creates a wave effect for the image which can be visualised more clearly by rotating the image
- Functions written are saved with the project
=> 3D depth function

pom.xml, src/main/java/sh/ball/gui/components/EffectComponentGroup.java, src/main/java/sh/ball/gui/components/EffectComponentGroupController.java, src/main/resources/CHANGELOG.md, src/main/resources/fxml/projectSelect.fxml
- Add additional decimal place on effect spinners so that the values change correctly
- Fixes #80
=> Fix spinners

src/main/java/sh/ball/shapes/Ellipse.java
yeah that's it, 1 line of code lol
=> Fix rotation not actually being applied to Ellipse objects

pom.xml, src/main/java/sh/ball/gui/components/CodeEditor.java, src/main/java/sh/ball/gui/controller/EffectsController.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/java/sh/ball/parser/lua/LuaSampleSource.java, src/main/java/sh/ball/parser/txt/FontStyle.java, src/main/resources/CHANGELOG.md, src/main/resources/fxml/projectSelect.fxml
Fixes #128 
Fixes #120 
Fixes #113
=> Various bug fixes

pom.xml, src/main/resources/CHANGELOG.md, src/main/resources/fxml/projectSelect.fxml, src/main/resources/lua/demo.lua
- Changed Lua demo file to the mini osci-render demo that emulates a basic version of osci-render within osci-render
- Done this as the old demo's audio was quite jarring and the new one shows off more of Lua
=> Update Lua demo file

pom.xml, src/main/java/sh/ball/audio/AudioPlayer.java, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/audio/midi/MidiNote.java, src/main/java/sh/ball/gui/Gui.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/java/sh/ball/gui/controller/ProjectSelectController.java, src/main/resources/CHANGELOG.md, src/main/resources/fxml/effects.fxml, src/main/resources/fxml/main.fxml, src/main/resources/fxml/projectSelect.fxml
- Dramatically improved MIDI performance! Should now be pretty resilient to anything you throw at it
- Renamed decay to release in MIDI settings
- Version number is now saved with .osci project file
=> Huge MIDI performance improvements

pom.xml, src/main/java/sh/ball/gui/GitHubReleaseDetector.java, src/main/java/sh/ball/gui/controller/ProjectSelectController.java, src/main/resources/CHANGELOG.md, src/main/resources/css/main.css, src/main/resources/fxml/projectSelect.fxml
- Add message to project select screen if there is a new version available
=> Implement GitHub new release detection on project screen

pom.xml, src/main/java/sh/ball/audio/ShapeAudioPlayer.java, src/main/java/sh/ball/audio/effect/WobbleEffect.java, src/main/java/sh/ball/audio/midi/MidiNote.java, src/main/java/sh/ball/gui/controller/MainController.java, src/main/resources/CHANGELOG.md, src/main/resources/fxml/projectSelect.fxml
- Improved MIDI support
- CC channels that are reserved and commonly used (e.g. channel volume, pan, etc.) are now reserved and cannot be used for controlling slider values
- Added support for changing the channel's volume using CC values
- Added support for changing the pitch bend range via RPN messages
- Fix Wobble effect stutter and frequency
=> Midi standard improvements

Source/PluginProcessor.cpp, osci-render.jucer
Fixes failed AU validation in Logic
=> Correctly support mono output

Source/LookAndFeel.cpp, Source/LookAndFeel.h, Source/audio/EffectParameter.h, osci-render.jucer
=> Fix audio input being disabled, improve checkbox design, allow lfo sliders to be more granular

Source/MainComponent.cpp, Source/PluginEditor.cpp, Source/PluginProcessor.cpp, Source/PluginProcessor.h, osci-render.jucer
=> Fix bug with opening older osci project files, and remember last opened directory

Source/MainComponent.cpp, Source/PluginEditor.cpp, Source/PluginEditor.h, Source/PluginProcessor.cpp, Source/PluginProcessor.h, Source/lua/LuaParser.cpp, Source/shape/Line.cpp, Source/shape/Line.h, osci-render.jucer
Adds the following functions to Lua for ease-of-use:
```lua
return osci_line(phase)
```
```lua
start = { slider_a, slider_b }
finish = { slider_c, slider_d }
line = osci_line(phase, start, finish)
return line
```
```lua
return osci_rect(phase)
```
```lua
width = slider_a
height = slider_b
rect = osci_rect(phase, width, height)
return rect
```
```lua
return osci_square(phase)
```
```lua
width = slider_a
square = osci_rect(phase, width)
return square
```
```lua
return osci_arc(phase)
```
```lua
radius_x = slider_a
radius_y = slider_b
start_angle = slider_c * 2 * math.pi
end_angle = slider_d * 2 * math.pi
arc = osci_arc(phase, radius_x, radius_y, start_angle, end_angle)
return arc
```
```lua
return osci_ellipse(phase)
```
```lua
radius_x = slider_a
radius_y = slider_b
ellipse = …
```
=> Add several Lua functions
