jameshball/osci-render

src/audio/AudioClient.java
src/audio/AudioPlayer.java
src/engine/Vector3.java
src/engine/WorldObject.java
src/shapes/Shapes.java

When the program runs it will now hang and pre-render the frames to be drawn on the screen. This helps improve performance when rendering complicated models and reduces the load on the computer if the same animation is rendered for a long amount of time.
TODO: Add verbose messages for pre-rendering progress.

Implement pre-rendering of frames

---

src/audio/AudioArgs.java
src/audio/AudioClient.java
src/audio/AudioPlayer.java
src/engine/Camera.java
src/engine/Vector3.java
src/engine/WorldObject.java
src/shapes/Ellipse.java
src/shapes/Line.java
src/shapes/Shape.java
src/shapes/Shapes.java
src/shapes/Vector2.java

- Passing in arguments for the position of the camera is not required
- Just pass in the object file (with optional rotation speed and focal length) and image scaling is done for you
- Position arguments can still be passed in to override the auto-scaling
- This moves the z-position of the camera and does a sample renders of the object being rotated
- By rotating the object we get an idea of the max abs. value its vertices can have
- We keep moving the camera back until the max abs. value is less than VERTEX_VALUE_THRESHOLD (Should stay at 1)
- Move argument processing out of AudioClient class into separate AudioArgs class
- Put frame pre-rendering in separate function in AudioClient
- Create another AudioPlayer constructor for code reduction in main

Implement image auto-scaling

---

pom.xml
src/main/java/sh/ball/audio/engine/ConglomerateAudioEngine.java
src/main/java/sh/ball/audio/engine/JavaAudioEngine.java
src/main/java/sh/ball/gui/Gui.java

Adds the JavaAudioEngine class that results in greater compatibility by using the Java Sound API rather than XtAudio.
- New 'default' audio device which is just the device that is currently set as default on the machine
- This changes when the default audio device is changed on the machine
- Potentially now supports MacOS (testing required)

Add JavaAudioEngine for greater compatibility

---

pom.xml
src/main/java/sh/ball/gui/Controller.java
src/main/java/sh/ball/gui/Gui.java
src/main/resources/fxml/osci-render.fxml

- Added 'Choose Folder' button to select a folder containing `.txt`, `.obj`, and `.svg` files
- Cycle between the files in the folder using `j` and `k` on your keyboard
- File choosers now remember the location you last opened a file from

Implement loading a whole folder of files

---

src/main/java/sh/ball/audio/midi/MidiCommunicator.java
src/main/java/sh/ball/audio/midi/MidiListener.java
src/main/java/sh/ball/audio/midi/MidiNote.java
src/main/java/sh/ball/gui/Controller.java
src/main/resources/fxml/osci-render.fxml

- First, plug-in MIDI device
- Open osci-render
- Click MIDI logo next to the slider you want to control
- Red means the slider is 'armed' and waiting for you to choose a MIDI key to associate it with
- Move a slider/knob etc. on your MIDI device
- The MIDI logo now turns green, and is controlled by your MIDI device!

Implement MIDI control of sliders

---

pom.xml
src/main/java/sh/ball/gui/Controller.java
src/main/java/sh/ball/gui/Gui.java
src/main/resources/fxml/osci-render.fxml

This pull request adds code for playback when a folder is selected, which play the files one by one at a selected framerate. When in playback mode, the hint about changing files changes to a hint about playback controls. Code is properly commented and has protections against common bugs such as setting invalid framerate values.
Changes:
```
Modified files:
- Gui.java (add hotkeys)
- Controller.java (add code for playback and UI modifications)
- osci-render.fxml (add info on playback controls to UI)
New hotkeys:
- i -> play opened files one by one
- u -> decrease playback rate, down to 1 frame per second
- o -> increase playback rate, up to 120 frames per second
```

Add Playback Controls for Multiple Files

---

pom.xml
src/main/java/sh/ball/gui/Controller.java

Sort the files in a directory in alphabetical order before selecting them, preventing issues on some systems where directories will open in strange, non-alphabetical orders.
(I recommend making this a 1.16.1 patch instead of 1.17.0 since this isn't a feature addition)

Add sorting to directory code

---

pom.xml
src/main/java/sh/ball/audio/ShapeAudioPlayer.java
src/main/java/sh/ball/gui/Controller.java
src/main/java/sh/ball/parser/svg/MoveTo.java
src/main/java/sh/ball/parser/svg/SvgParser.java

- Much better rendering of complex shapes, particularly SVGs with a lot of detail
- e notation in SVG paths is now supported
- e.g. 7e-5
closes #40

Support e notation in SVGs, and correctly skip over small shapes when rendering

---

pom.xml
src/main/java/sh/ball/audio/FrameProducer.java
src/main/java/sh/ball/audio/FrameSource.java
src/main/java/sh/ball/audio/ShapeAudioPlayer.java
src/main/java/sh/ball/engine/WorldObject.java
src/main/java/sh/ball/gui/Controller.java
src/main/java/sh/ball/parser/obj/ObjFrameSettings.java
src/main/java/sh/ball/parser/obj/ObjFrameSource.java
src/main/java/sh/ball/parser/obj/ObjSettingsFactory.java
src/main/java/sh/ball/shapes/ShapeFrameSource.java

- Increases `BUFFER_SIZE` in `ShapeAudioPlayer` to reduce audio glitches
- Maintain rotation information between 3D objects properly
- Draw 3D objects in a consistent order
- They are now deterministically drawn and always sound the same

Smoothly transition between objects, and have consistent sound for all objects

---

pom.xml
src/main/java/sh/ball/parser/obj/ObjFrameSource.java
src/main/java/sh/ball/parser/svg/SvgParser.java
src/main/java/sh/ball/shapes/Shape.java

- `SVGParser` now looks at `viewBox`, `width`, and `height` attributes of the `svg` tag
- Shapes are normalised according to this. They are scaled according to the max-absolute dimension
- Currently ignoring `min-x` and `min-y`
- Change base rotation so that it is no longer rendered upside-down for objects
https://user-images.githubusercontent.com/38670946/146999774-a5c16f45-c124-44d1-86fd-afea2e073d3a.mp4

Use viewBox and width/height to correctly render SVGs

---

CHANGELOG.md
pom.xml
src/main/java/sh/ball/gui/controller/ImageController.java
src/main/java/sh/ball/gui/controller/MainController.java
src/main/resources/fxml/effectComponentGroup.fxml
src/main/resources/fxml/main.fxml

- Effect text boxes are now editable
- Version number now visible in File menu
- You can now double-click sliders to reset their values to minimum

Add version to interface and improve slider usability

---

pom.xml
src/main/java/sh/ball/audio/effect/EffectType.java
src/main/java/sh/ball/audio/effect/PerspectiveEffect.java
src/main/java/sh/ball/gui/controller/EffectsController.java
src/main/java/sh/ball/gui/controller/MainController.java
src/main/resources/CHANGELOG.md
src/main/resources/fxml/effects.fxml
src/main/resources/fxml/projectSelect.fxml

- Add reset 2D rotation button to effects
- Add reset 3D perspective rotation button to effects
- Correctly show recent files under File menu when starting a new project
- Minor changes to perspective effect
- Added a new '3D Distance' effect that functions the same as the '3D Perspective' effect in the previous version
- Changed the '3D Perspective' effect so that a value of 0 applies no change to the image
- This makes it in-line with most other effects, where a value of 0 doesn't affect the image
- Default value is 1.0 which has the depth effect fully applied
- Values between 0.0 and 1.0 mix the effect to make a cool image!

Add reset rotation buttons and other small changes

---

src/main/java/sh/ball/shapes/Line.java

double min = dy <= dx ? dx : dy;
This was previously wrong (calculated the maximum instead of minimum) and also inefficient
double max = dy > dx ? dy : dx;
This was previously right, but was still inefficient
Last small bugfix for now, I thought I had more, but since I'm going through every single file there will be more eventually. Almost 100%. However, your code is really well written and understandable, so I've been porting everything to C++ smoothly. Should be a few more days of work, but not a few weeks.

Make Line.getLength() work (in 2 fewer lines)

---

pom.xml
src/main/java/sh/ball/gui/Gui.java
src/main/resources/CHANGELOG.md
src/main/resources/fxml/effects.fxml
src/main/resources/fxml/main.fxml
src/main/resources/fxml/projectSelect.fxml

Allows project select screen and main interface to be resized. If anyone has any feedback please let me know! You should notice very few changes if you don't change the size of the windows like before.

Resizable windows - feedback please!

---

.github/workflows/release.yml
README.md
pom.xml
src/main/java/sh/ball/audio/AudioPlayer.java
src/main/java/sh/ball/audio/FrequencyAnalyser.java
src/main/java/sh/ball/audio/ShapeAudioPlayer.java
src/main/java/sh/ball/gui/controller/EffectsController.java
src/main/java/sh/ball/gui/controller/MainController.java
src/main/java/sh/ball/gui/controller/VolumeController.java
src/main/resources/CHANGELOG.md
src/main/resources/css/main.css
src/main/resources/fxml/effects.fxml
src/main/resources/fxml/main.fxml
src/main/resources/fxml/projectSelect.fxml
src/main/resources/fxml/volume.fxml

- Updated osci-render to Java 19 (please report any new issues you think could be related to this!)
- Added volume slider on right side of main interface
- This replaces the volume scale slider under audio effects
- The slider has a volume visualiser that shows the current volume in the left and right audio channels
- It also shows the average volume
- There is also another slider that points to the volume slider that controls the hard clipping point of the audio
- The hard clipping point is the point at which the audio is clipped to the maximum volume
- Any samples above this point are set to this point
- By default, this is set to 1 meaning that any values less than -1 or greater than 1 are set to -1 or 1 respectively

Volume visualiser + Java 19

---

pom.xml
src/main/java/sh/ball/audio/effect/EffectAnimator.java
src/main/java/sh/ball/gui/components/EffectComponentGroupController.java
src/main/java/sh/ball/parser/txt/TextParser.java
src/main/resources/CHANGELOG.md
src/main/resources/css/main.css
src/main/resources/fxml/projectSelect.fxml

- Allow text size to be specified when creating .txt files
- Write "$text_size=" followed by a number to change the text size for that line
- e.g. "$text_size=50" will make the text size 50 for that line
- The default text size is 100
- If for some reason you still want to write "$text_size=", you can escape it with a backslash. e.g. "\\$text_size=50"
- This slightly changes the syntax for writing a backslash, as you now need to write "\\\\" instead of "\\"
- Fix a bug where the animations would get stuck if the bounds of the slider/effect were changed while the animation was playing
- The knobs/thumbs of sliders now change to green when the slider/effect is being animated

Small fixes/improvements to text files and animations

---

pom.xml
src/main/java/sh/ball/audio/AudioUtil.java
src/main/java/sh/ball/audio/ShapeAudioPlayer.java
src/main/java/sh/ball/audio/effect/AudioProcessorEffect.java
src/main/java/sh/ball/audio/effect/BulgeEffect.java
src/main/java/sh/ball/audio/effect/DelayEffect.java
src/main/java/sh/ball/audio/effect/EffectType.java
src/main/java/sh/ball/gui/controller/EffectsController.java
src/main/java/sh/ball/shapes/Vector2.java
src/main/resources/CHANGELOG.md
src/main/resources/fxml/effects.fxml
src/main/resources/fxml/projectSelect.fxml

- Added two new audio effects: Delay/Echo and Bulge
- Delay effect can be used to create an echo of the audio signal
- Controllable with both the echo length and the decay of the echo
- Bulge effect makes the image bulge outwards
- If you change the minimum slider value to something negative using the Slider settings, you can make the image bulge inwards

Delay and Bulge effects

---

Source/PluginEditor.cpp
Source/PluginEditor.h
osci-render.jucer

Leads to massively improved performance of the interface on Windows, closing #177

Enable OpenGL on Windows and Linux

---

Source/PluginProcessor.cpp
Source/PluginProcessor.h
Source/audio/Effect.cpp
Source/audio/Effect.h
Source/audio/EffectParameter.h
Source/components/EffectComponent.cpp
Source/components/EffectComponent.h
Source/components/EffectsListComponent.cpp
osci-render.jucer

Demo (unmute audio):
https://github.com/jameshball/osci-render/assets/38670946/e79e63f4-1b7b-4e78-b027-e27e4802f5df
Changes in this version:
- Adds sidechain ability, allowing you to change the value of effects based on the volume of the input audio
- You can enable this for any slider by clicking the microphone icon next to it
- When enabled, the microphone icon and slider turn red
- Now, any audio input controls the value of the effect
- Closes #189 
- Sliders are now more usable when the interface is made smaller
- When loading a project, the DAW is now properly notified of any changes in values
- Closes #181 
- Reduce how dark disabled audio effects are, so they are easier to read
- Closes #190

Add sidechain functionality to allow effects to react to audio input volume

---

Source/MidiComponent.cpp
Source/MidiComponent.h
Source/PluginEditor.cpp
Source/audio/ShapeVoice.cpp
Source/obj/ObjectServer.cpp
osci-render.jucer

Various bugs and improvements:
- Fixes min trace and max trace effects, so they work as expected
- Improves audio performance
- Fixes a bug that meant osci-render could crash when rendering a Blender scene
- Adds a button to open the Audio and MIDI settings from the MIDI panel when running the standalone version
Closes #211 
Closes #210

Fix min/max trace, improve rendering performance, fix dodgy Blender message reading, add button to open MIDI settings

---

Source/MainComponent.cpp
Source/PluginEditor.cpp
Source/PluginEditor.h
Source/components/DraggableListBox.cpp
Source/components/EffectComponent.cpp
osci-render.jucer

- Fixed bug where custom Lua effect code would be blank when opening and closing a VST window
- Fixed bug where enabling sidechain on the first parameter in an effect causes sidechain on all parameters to be enabled
- Fixed crash when reordering effects
- Changed AU plugin type so it appears correctly as an instrument in GarageBand
- Osci-render now automatically opens the code editor when a Lua or text file is created
Closes #231 #230

Various bug fixes and improvements

---

blender/osci_render/__init__.py
blender/osci_render/blender_manifest.toml

It looks like they've rolled back (or at least reduced the stringency of) the requirement to supply blender_manifest.toml with the plugin! Therefore, this PR only contains the required code changes to get the plugin working in 4.3.

Update __init__.py to work in Blender 4.3

---

Source/CommonPluginEditor.cpp
Source/CommonPluginProcessor.cpp
Source/CommonPluginProcessor.h
Source/components/OsciMainMenuBarModel.cpp
Source/components/SosciMainMenuBarModel.cpp
Source/components/SosciMainMenuBarModel.h
Source/visualiser/VisualiserComponent.cpp

This update adds a setting to enable or disable intercepting special keys (such as ctrl-s and the spacebar). This setting is enabled by default on the standalone and disabled by default on plugins, as plugins intercepting these shortcuts can be very annoying when working in a DAW.

Interaction toggle

---

Source/PluginProcessor.h
Source/audio/PerspectiveEffect.h
Source/obj/Camera.cpp
Source/obj/Camera.h
Source/obj/Frustum.cpp
Source/obj/Frustum.h

* Place camera such that view frustum is always tangent to unit sphere
* A normalized shape at any orientation with any FOV will now always be perfectly within bounds
* Expose camera FOV instead of focal length
* This allows for a more linear-feeling response throughout the whole range of the slider

Perspective improvements

---

Source/PluginProcessor.cpp
Source/PluginProcessor.h
Source/audio/DashedLineEffect.h

* Dashed line effect is now configured to draw a user-specified number of dashes per frame regardless of frequency
* Implemented by allowing the dash clock to have period of non-integer number of samples
* Variable dash coverage
* What percentage of "dash unit" is filled in vs left blank
* At 0%, this effect behaves like a downsampler

Make dash frequency invariant and smoother

---

Resources/lua/hypercube.lua
Resources/lua/mushroom.lua
Resources/lua/spiral.lua

* Use Eulerian cycle traversal to remove all instant jumps
* Normalize vertices and perspective projection
* Make 3D
* Normalize
* Normalized for default height and y offset values - so if users change them, the visuals will properly reflect the changes
* Reduce number of default loops so they are better represented at default frequency and typical sample rate
* Correct frequency

Hypercube, Mushroom, Spiral example improvements

---

Source/components/VListBox.cpp

On line 169, setting the second parameter to `false` makes the `juce::Component content` never get deleted, causing a memory leak. This PR switches it to `true`, which fixes the issue by deleting the `juce::Component` once it's no longer needed.

Fix memory leak in VListBox.cpp
